version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/booksdb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  mongo-test:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - mongo-test-data:/data/db

volumes:
  mongo-data:
  mongo-test-data:
